apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-champion-ox
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "361124713625"
    provider: eks
    region: ap-southeast-2
    registry: 361124713625.dkr.ecr.ap-southeast-2.amazonaws.com
  environments:
  - key: dev
    owner: xzfvictor
    repository: jx3-eks-vault
  - key: staging
  - key: production
  ingress:
    domain: 54.66.180.91.nip.io
    externalDNS: false
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: xzfvictor
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-tf-jx-champion-ox-20210308104802862100000006
  - name: reports
    url: s3://reports-tf-jx-champion-ox-20210308104802866500000007
  - name: repository
    url: s3://repository-tf-jx-champion-ox-20210308104802856300000005
  terraform: true
  vault:
    aws:
      dynamoDBRegion: ap-southeast-2
      dynamoDBTable: vault-unseal-tf-jx-champion-ox-oFyPE1zl
      kmsKeyId: d4eed35a-25f1-4ea6-8ff5-e0f7851c3fb1
      kmsRegion: ap-southeast-2
      s3Bucket: vault-unseal-tf-jx-champion-ox-20210308104802855800000003
      s3Region: ap-southeast-2
  webhook: lighthouse
