apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - xzfvictor/jx3-eks-vault
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - xzfvictor/jx-python-http
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    heart: {}
    label:
      additional_labels: null
    owners: {}
    plugins:
      xzfvictor/jx-python-http:
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
      xzfvictor/jx3-eks-vault:
      - config-updater
      - approve
      - assign
      - blunderbuss
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - heart
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - xzfvictor/jx3-eks-vault
      trusted_org: todo
    - repos:
      - xzfvictor/jx-python-http
      trusted_org: todo
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
