# Source: lighthouse/templates/keeper-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lighthouse-keeper
  labels:
    chart: "lighthouse-0.0.939"
    app: lighthouse-keeper
    gitops.jenkins-x.io/pipeline: 'namespaces'
  namespace: jx
  annotations:
    wave.pusher.com/update-on-config-change: 'true'
    jenkins-x.io/hash: '1386d820da9abc723201c8185f1be0c88a5eadea2b4c00c2af600ed179826210'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: lighthouse-keeper
  template:
    metadata:
      annotations:
        ad.datadoghq.com/keeper.logs: '[{"source":"lighthouse","service":"keeper"}]'
      labels:
        app: lighthouse-keeper
    spec:
      serviceAccountName: lighthouse-keeper
      terminationGracePeriodSeconds: 30
      containers:
        - name: lighthouse-keeper
          image: gcr.io/jenkinsxio/lighthouse-keeper:0.0.939
          imagePullPolicy: IfNotPresent
          args:
            - "--namespace=jx"
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: "GIT_KIND"
              value: "github"
            - name: "GIT_SERVER"
              value: "https://github.com"
            - name: "GIT_USER"
              value: xzfvictor
            - name: "GIT_TOKEN"
              valueFrom:
                secretKeyRef:
                  name: lighthouse-oauth-token
                  key: oauth
            - name: "JX_LOG_FORMAT"
              value: "json"
            - name: "LOGRUS_FORMAT"
              value: "json"
            - name: "LIGHTHOUSE_KEEPER_STATUS_CONTEXT_LABEL"
              value: "Lighthouse Merge Status"
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi
